config/routes.rb
Rails.application.routes.draw do
  get 'relationships/followings'
  get 'relationships/followers'
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'hello/index' => 'hello#index'
  get 'hello/link' => 'hello#link'
  root 'hello#index'
  resources :users, only: [:show]
  resources :posts do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end
  resources :users do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
    member do
      get :followings, :followers
     end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user
  validates_uniqueness_of :post_id, scope: :user_id
end

app/models/post.rb
class Post < ApplicationRecord
  mount_uploader :image, ImageUploader
    belongs_to :user
    has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user
  has_many :comments, dependent: :destroy
  
end

app/models/relationship.rb
class Relationship < ApplicationRecord
    belongs_to :follower, class_name: "User"
    belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_posts, through: :likes, source: :post
  has_many :comments, dependent: :destroy
  validates :name, presence: true 
  validates :profile, length: { maximum: 200 }
  mount_uploader :icon, ImageUploader
  has_many :relationships, foreign_key: :follower_id, dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: :followed_id, dependent: :destroy
has_many :followings, through: :relationships, source: :followed
has_many :followers, through: :reverse_of_relationships, source: :follower
  def already_liked?(post)
    self.likes.exists?(post_id: post.id)
  end
  def follow(user_id)
    relationships.create(followed_id: user_id)
  end
  
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end
  
  def following?(user)
    followings.include?(user)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
   
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :icon])
    
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :profile, :icon])
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :authenticate_user!
      
        def create
          post = Post.find(params[:post_id])
          comment = post.comments.build(comment_params) 
          comment.user_id = current_user.id
          if comment.save
            flash[:success] = "コメントしました"
            redirect_back(fallback_location: root_path) 
          else
            flash[:success] = "コメントできませんでした"
            redirect_back(fallback_location: root_path) 
        end
    end
    def destroy
      comment = Comment.find(params[:id])
      if comment.destroy
        redirect_to post_path(params[:post_id])
      else
        flash.now[:alert] = 'コメント削除に失敗しました'
        render post_path(params[:post_id])
      end
    end
    
    
      
        private
        def set_post
          @post = Post.find(params[:post_id])
        end
      
          def comment_params
            params.require(:comment).permit(:content)
          end
      end
    

app/controllers/hello_controller.rb
class HelloController < ApplicationController
    def index
        end
        def link
        end
    end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    def create
        like = current_user.likes.create(post_id: params[:post_id]) 
        redirect_back(fallback_location: root_path)
      end
    
      def destroy
        like = Like.find_by(post_id: params[:post_id], user_id: current_user.id)
        like.destroy
        redirect_back(fallback_location: root_path)
      end

    
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
   
      def index

        if params[:search] == nil
          @posts= Post.all
        elsif params[:search] == ''
          @posts= Post.all
        else
          @posts = Post.where("body LIKE ? ",'%' + params[:search] + '%')
      end

    end

        def new
            @post = Post.new
     end

        def create
            post = Post.new(post_params)
            post.user_id = current_user.id
            if post.save
              redirect_to :action => "index"
            else
              redirect_to :action => "new"
        end
     end

          def show
            @post = Post.find(params[:id])
            @comments = @post.comments
            @comment = Comment.new
          end

          def edit
            @post = Post.find(params[:id])
          end

          def update
            post = Post.find(params[:id])
            if post.update(post_params)
              redirect_to :action => "show", :id => post.id
            else
              redirect_to :action => "new"
            end
          end 

          def destroy
            post = Post.find(params[:id])
            post.destroy
            redirect_to action: :index
          end
          private
          def post_params
            params.require(:post).permit(:body, :image,)
          end
    end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def create
    current_user.follow(params[:user_id])
    redirect_to request.referer
  end
  
  def destroy
    current_user.unfollow(params[:user_id])
    redirect_to request.referer  
  end
  
  def followings
    user = User.find(params[:user_id])
    @users = user.followings
  end
  
  def followers
    user = User.find(params[:user_id])
    @users = user.followers
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def show
        @user = User.find(params[:id]) 
      end
    before_action :set_user, only: [:followings, :followers]
    def followings
      @users = @user.followings
    end
  
    def followers
      @users = @user.followers
    end
  
  private
    def set_user
      @user = User.find(params[:id])
    end
  end
  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/hello_helper.rb
module HelloHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/hello/index.html.erb
<%= link_to "ログイン", posts_path %>
<%= link_to "新規登録", new_user_registration_path %>

app/views/hello/link.html.erb
My name is GeekSalon.
<%= link_to 'トップページ', hello_index_path %>
<%= link_to '一覧表示', :controller => "posts", :action => "index" %>

app/views/layouts/application.html.erb
<html>
  <head>
    <title>GeekInstagram</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/8d3d28f6ac.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%#= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  </head>

  <body>
    <header>
      <h1>GeekInstagram</h1>
      <div class="header-list">
      <ul>
        <li><%= link_to "ホーム", posts_path %></li>
        <li><%= link_to "新規投稿",new_post_path %></li>
        <% if user_signed_in? %>
        <li><%= link_to "マイページ", user_path(current_user.id) %></li>
        <li>
        <% end %>
        <%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
        </ul>
      </div>
    </header>
    <main>
      <%= yield %>
    </main>
    
    
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

app/views/posts/edit.html.erb
<%= form_for @post do |f| %>
  <%= f.label :body %>
  <%= f.text_field :body, :size => 140 %> 
  <%= f.submit "編集" %>
<% end %>

app/views/posts/index.html.erb
<%= stylesheet_link_tag 'index', :media => "all" %>
<div class="posts-container">

  <h3>投稿一覧</h3>
  <div class="ser">
    <h3>投稿検索</h3>
    <%= form_tag({controller:"posts",action:"index"}, method: :get) do %>
      <%= text_field_tag :search %>
      <%= submit_tag '検索'  %>
    <% end %>
  </div>
</div>

<div class="container-fluid">
  <div class="row">
    <% @posts.each do |t| %>
      <div class="col-sm-4 col-12">
        <div class="card" style="width: 18rem;">
          <div class="card-body">
            <h5 class="card-title"><%= t.body %></h5>
            <p class="card-text"><%= t.created_at %></p>
            <%= link_to t.user.name, user_path(t.user.id) %>
            <figure class="icon-circle">
              <%= image_tag t.user.icon_url, size: "250x200" if t.user.icon? %>
            </figure>
            <%= t.body %>
            <%= image_tag t.image_url, size: "650x600" if t.image? %>
            <div class="main-box">
              <div class="left-container">
                <% if user_signed_in? %>
                  <% if current_user.already_liked?(t) %>
                    <%= link_to post_like_path(id: t.id, post_id: t.id), method: :delete do %>
                      <i class="fas fa-heart"></i><%= t.likes.count %>
                    <% end %>
                  <% else %>
                    <%= link_to post_likes_path(id: t.id, post_id: t.id), method: :post do %>
                      <i class="far fa-heart"></i><%= t.likes.count %>
                    <% end %>
                  <% end %>
                <% else %>
                  <i class="far fa-heart"></i><%= t.likes.count %>
                <% end %>
              </div>
              <div class="right-container">
                <%= link_to "詳細", post_path(t.id) %>
                <% if user_signed_in? && current_user.id == t.user_id %>
                  <%= link_to "編集", edit_post_path(t.id) %>
                  <%= link_to "削除", post_path(t.id), method: :delete %>
                <% end %> 
              </div>
            </div>
          </div>
          <p class="time"><%= t.created_at %></p>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/posts/new.html.erb
<%= stylesheet_link_tag 'new', :media => "all" %>

<div class="post-container">
  <p class="title">投稿フォーム</p>
  <%= form_for(@post, :url => { controller:'posts', action:'create'})do |f| %>
    <%= f.label :投稿内容 %>
        <br>
        <%= f.text_field :body,size: 140%>
        <br>
      <div class="field">
        <%= f.label :image %>
        <%= f.file_field :image %>
      </div>
    <%= f.submit "送信"%>
    <br>
  <% end %>
</div>

app/views/posts/show.html.erb
<h3>投稿詳細</h3>
<div class="post">
  <p><%= @post.user.email %></p>
  <p><%= @post.body %></p>
  <p><%= @post.created_at %></p>
    <% if user_signed_in? %>
      <% if current_user.already_liked?(@post) %>
          <%= link_to post_like_path(@post), method: :delete do %> 
            <i class="fas fa-heart"></i><%= @post.likes.count %>   
          <% end %>
      <% else %>
          <%= link_to post_likes_path(@post), method: :post do %>
              <i class="far fa-heart"></i><%= @post.likes.count %>
          <% end %>
      <% end %>
    <% else %>  
      <i class="far fa-heart"></i><%= @post.likes.count %> 
    <% end %>
</div>

<h2>いいねしたユーザー</h2>
<% @post.liked_users.each do |user| %>
  <li><%= user.email %></li>
<% end %>
  

<div class="comment-wrapper">
  <h5>コメント一覧</h5>
  <% @comments.each do |c| %>
    <div>
      <%= c.user.email unless c.user.blank? %>
      <br>
      <%= c.content %>
      <% if user_signed_in? && current_user.id== c.user_id %>
      <%= button_to "削除", post_comment_path(c.post.id, c.id), method: :delete %>
      <% end %>

    </div>
      <br>
  <% end %>

  <% if user_signed_in? %>
    <%= form_with(model: [@post, @comment], local: true) do |f| %>
      <%= f.text_area :content %>
      <%= button_tag type: "submit" do %>
        <i class="far fa-comments"></i> コメントする
      <% end %>
    <% end %>
  <% end %>
</div>

<%= link_to "投稿一覧に戻る", posts_path %>

app/views/relationships/_follow_list.html.erb
<% if users.exists? %>
  <% users.each do |user| %>
    <table>
      <thead>
        <tr>
          <th>name</th>
          <th></th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td><%= user.name %></td>
          <td>フォロー数: <%= user.followings.count %></td>
          <td>フォロワー数: <%= user.followers.count %></td>
        </tr>
      </tbody>
    </table>
  <% end %>
<% else %>
  <p>ユーザーはいません</p>
<% end %>

app/views/relationships/followers.html.erb
<p>フォロワー一覧</p><br/>
  <% @users.each do |user| %>
  <%= user.name %>
<% end %>

app/views/relationships/followings.html.erb
<p>フォロー一覧</p><br/>
  <% @users.each do |user| %>
  <%= user.name %>
<% end %>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "ログイン", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "アカウント作成", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "パスワードをお忘れですか?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<h1>ユーザーページ</h1>
<figure class="icon-circle">
  <%= image_tag @user.icon_url, size: "250x200" if @user.icon.present? %>
</figure>
<% if current_user.following?(@user) %>
  <%= link_to "フォロー外す", user_relationships_path(@user.id), method: :delete %>
<% else %>
  <%= link_to "フォローする", user_relationships_path(@user.id), method: :post %>
<% end %>
<%= link_to "フォロー", followings_user_path(@user) %>
<%= link_to "フォロワー", followers_user_path(@user) %>
<p>名前 : <%= @user.name %></p>
<p>メールアドレス : <%= @user.email %></p>
<p>プロフィール : <%= @user.profile %></p>
<% if current_user.id == @user.id %>
  <%= link_to "編集する", edit_user_registration_path %>
<% end %>

<h2>ユーザーの投稿一覧</h2>
<% @user.posts.each do |t| %>
  <%= t.user.name %>
  <%= t.body %>
<% end %>


<h2>ユーザーがいいねした投稿一覧</h2>
<% @user.liked_posts.each do |t| %>
  <%= t.user.name %>
  <%= t.body %>
<% end %>


<%= link_to "一覧に戻る", posts_path %>